Support for custom url endpoint. Example for Yandex object storage
cuba-platform/cuba-aws pull request #1
Opened 2019-12-17 09:08 UTC by basicus

Hello, please check and It is OK accept pull request

2019-12-17 09:08 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cuba-platform/cuba-aws?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cuba-platform/cuba-aws?pullRequest=1) before we can accept your contribution.<br/><hr/>**Сергей Бутенин** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cuba-platform/cuba-aws?pullRequest=1) it.</sub>

2019-12-23 09:16 UTC, andreysubbotin requested changes

2019-12-23 09:16 UTC, andreysubbotin commented on modules/core/src/com/haulmont/addon/cubaaws/s3/AmazonS3Config.java
> +    String getEndPoint();
Perhaps you should rename to cuba.amazonS3.endpointUrl and getEndpointUrl

2019-12-23 14:13 UTC, basicus commented on modules/core/src/com/haulmont/addon/cubaaws/s3/AmazonS3Config.java
> +    String getEndPoint();
Andrey, I renamed parameter and function.
And please review for fix in function fileExists. 

This code is in my production  system.

2019-12-23 16:49 UTC, andreysubbotin approved these changes

2019-12-24 06:20 UTC, merged